[project]
name = "p10-dsml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "easyocr>=1.7.2",
    "faiss-cpu==1.10.0",
    "langchain==0.3.23",
    "langchain-mistralai>=0.2.12",
    "logfire>=4.15.1",
    "mistralai>=1.0.0",
    "numpy>=2.3.5",
    "openpyxl==3.1.5",
    "pandas==2.2.3",
    "pillow>=9.0.0",
    "psycopg2>=2.9.11",
    "pymupdf>=1.22.0",
    "pypdf2==3.0.1",
    "python-docx==1.1.2",
    "python-dotenv==1.1.0",
    "ragas>=0.3.9",
    "requests==2.32.3",
    "streamlit==1.44.1",
    "streamlit-feedback==0.1.4",
    "tqdm>=4.67.1",
]
